modLoader="javafml"
loaderVersion="[31,)"
license="${license}"
issueTrackerURL="https://github.com/vakiliner/MusicPack/issues"

[[mods]]
modId="musicpack"
version="${version}"
displayName="Music Pack"
description='''
Музыкальный пакет для VAKiliner Hide And Seek
'''
logoFile="pack.png"
updateJSONURL="https://raw.githubusercontent.com/vakiliner/MusicPack/refs/heads/main/update.json"
authors="VAKiliner"
displayURL="https://github.com/vakiliner/MusicPack"

[[dependencies.musicpack]]
	modId="forge"
	mandatory=true
	versionRange="[31.2.44,32),[32.0.72,)"
[[dependencies.musicpack]]
	modId="minecraft"
	mandatory=false
	versionRange="[1.16,1.17)"